### ISSUE TITLE
Undeclared dependency

### ISSUE THREAD

**Issue by iandanforth-alation** [microsoft/FOST#2]
It appears that `torch-sparse` is also required.

![image](https://user-images.githubusercontent.com/52720125/141503975-6cc178c7-f61b-4976-8b32-c8990b285799.png)

**Comment by chlxydl** [comment]
Yes, it is actually required by the torch-germetric, you can go through the pyg installation [document](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html) for installation.
